---
title: "Aaron Project 2"
author: "Aaron Rock"
date: "2022-10-19"
output: html_document
---
```{r init, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
library(gmodels)
library(ggplot2)
library(dplyr)
install.packages("matrixStats")
library(matrixStats)
library(corrplot)
library(FNN)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```


```{r}
#First, load the file
online = data.frame(read.csv("online_shoppers_intention.csv"))
original_online = data.frame(read.csv("online_shoppers_intention.csv"))
head(online)
```
```{r, results='hide'}
# Handling categorical variables prior to plotting
online$Month = as.factor(online$Month)
online$Revenue = as.factor(online$Revenue)
online$Weekend = as.factor(online$Weekend)
online$VisitorType = as.factor(online$VisitorType)
```

``` {r}
monthFrequency = ggplot(online, aes(x=Month, color=Month, fill=Month)) + geom_bar()
monthFrequency
userCount = ggplot(online, aes(x=VisitorType, color=VisitorType, fill=VisitorType)) + geom_bar()
userCount
revCount = ggplot(online, aes(x=Revenue, color=Revenue, fill=Revenue)) + geom_bar()
revCount
revTrue = subset(online, online$Revenue == TRUE)
revFalse = subset(online, online$Revenue == FALSE)
pieNum <- c(nrow(revTrue), nrow(revFalse))
piepercent<- round(100*pieNum/sum(pieNum), 1)
pie(pieNum, labels = piepercent, main = "Revenue Percentages",col = rainbow(length(pieNum)))
legend("topright", c("True","False"), cex = 0.8, fill = rainbow(length(pieNum)))
```
```{r}
# Special Day data
specialDay = ggplot(online, aes(SpecialDay)) + geom_density(color="darkblue", fill="lightblue")
specialDay
# scatterSpecialDay = ggplot(online, aes(Revenue, SpecialDay)) + geom_violin(), this plot had no significance
```

```{r}
adminDur = ggplot(online, aes(Administrative_Duration, color=Revenue, fill=Revenue)) + geom_histogram(bins=30)
adminDur
infoDur = ggplot(online, aes(Informational_Duration, color=Revenue, fill=Revenue)) + geom_histogram(bins=30)
infoDur
prodDur = ggplot(online, aes(ProductRelated_Duration, color=Revenue, fill=Revenue)) + geom_histogram(bins=30)
prodDur
```

```{r}
# Bounce Rate is measured by total one page visits divided by total visits 
bounceBox = ggplot(online, aes(BounceRates)) + geom_boxplot(color='blue')
bounceBox
# Exit Rate is measured by total exits from page divided by total visits to page
exitBox = ggplot(online, aes(ExitRates)) + geom_boxplot(color='orange')
exitBox
```
The average Bounce Rate for this site is `r mean(online$BounceRates)*100`%.
The average Exit Rate for this site is `r mean(online$ExitRates)*100`%.

For our dataset it would be better to see individual page exit and bounce rates. The column variables Exit and Bounce Rates are the average of these metrics over each page on this site.


```{r}
online_new = subset(online, select = -c(VisitorType, Month))
online_new$Weekend = as.numeric(online_new$Weekend)
online_new$Revenue = as.numeric(online_new$Revenue)
corrOnline <- cor(online_new)
corrplot(corrOnline, method="number",number.cex=0.5,tl.cex=.6)
```


```{r}
monthTable = xtabs( ~ Revenue + Month, data = online)
monthTable
chisqMonth = chisq.test(monthTable)
chisqMonth
```

```{r}
specialDayTable = xtabs( ~ Revenue + SpecialDay, data = online)
specialDayTable
chisqSD = chisq.test(specialDayTable)
chisqSD
```

```{r, results='hide'}
library(tidyr)
# Rehandle
online$VisitorType = as.factor(online$VisitorType)
online$Weekend = as.integer(online$Weekend)
online$OperatingSystems = as.integer(online$OperatingSystems)
online$Browser = as.integer(online$Browser)
online$TrafficType = as.integer(online$TrafficType)
online$Region = as.integer(online$Region)
online$Month = as.integer(factor(online$Month, levels = month.abb))
online = drop_na(online)
# Making Visitor Type into numerical variable
library(tidyverse)
online$VisitorType <- str_replace(online$VisitorType,'New_Visitor','1')
online$VisitorType <- str_replace(online$VisitorType,'Other','2')
online$VisitorType <- str_replace(online$VisitorType,'Returning_Visitor','3')
online$VisitorType = as.numeric(online$VisitorType)
```


```{r, results='hide'}
# PageValues + Month + ExitRates + ProductRelated_Duration + TrafficType + VisitorType + ProductRelated
original_online$VisitorType = as.factor(original_online$VisitorType)
original_online$Weekend = as.integer(original_online$Weekend)
original_online$OperatingSystems = as.integer(original_online$OperatingSystems)
original_online$Browser = as.integer(original_online$Browser)
original_online$TrafficType = as.integer(original_online$TrafficType)
original_online$Region = as.integer(original_online$Region)
original_online$Month = as.integer(factor(original_online$Month, levels = month.abb))
original_online = drop_na(online)
# Making Visitor Type into numerical variable

original_online$VisitorType <- str_replace(original_online$VisitorType,'New_Visitor','1')
original_online$VisitorType <- str_replace(original_online$VisitorType,'Other','2')
original_online$VisitorType <- str_replace(original_online$VisitorType,'Returning_Visitor','3')
original_online$VisitorType = as.numeric(original_online$VisitorType)

original_online = subset(original_online, select = -c(1,2,3,4,7,10,12,13,14,17))
```

```{r}
scaledOnline <- as.data.frame(scale(online[1:17], center = TRUE, scale = TRUE))
```

```{r}
# Selected Variables based off EDA
scaled_Online_select <- as.data.frame(scale(original_online[1:7], center = TRUE, scale = TRUE))
```

```{r}
set.seed(123)
online_sample <- sample(2, nrow(scaledOnline), replace=TRUE, prob=c(0.80, 0.20))
```

```{r}
# Selected Variables Model based off EDA
set.seed(123)
online_sample_selected <- sample(2, nrow(scaled_Online_select), replace=TRUE, prob=c(0.8, 0.2))
```


```{r}
online_training <- scaledOnline[online_sample==1, 1:17]
online_test <- scaledOnline[online_sample==2, 1:17]
```

```{r}
# Selected Variables Model based off EDA
online_training_selected <- scaled_Online_select[online_sample_selected==1, 1:7]
online_test_selected <- scaled_Online_select[online_sample_selected==2, 1:7]
```


```{r}
online_trainLabels <- online[online_sample==1, 18]
online_testLabels <- online[online_sample==2, 18]
```

```{r}
# Selected Variables Model based off EDA
online_trainLabels_selected <- original_online[online_sample_selected==1, 8]
online_testLabels_selected <- original_online[online_sample_selected==2, 8]
```

```{r, results='hide'}
ResultDf = data.frame( k=numeric(0), Total.Accuracy= numeric(0), row.names = NULL )

ResultDf_selected = data.frame( k=numeric(0), Total.Accuracy= numeric(0), row.names = NULL )
```

```{r}
for (kval in 5:25) {
  online_pred <- knn(train = online_training, test = online_test, cl=online_trainLabels, k=kval)
  onlinePREDCross <- CrossTable(online_testLabels, online_pred, prop.chisq = FALSE)
  print( paste("k = ", kval) )
  onlinePREDCross
  
  cm = confusionMatrix(online_pred, reference = online_testLabels ) 
  cmaccu = cm$overall['Accuracy']
  print( paste("Total Accuracy = ", cmaccu ) )
   
  cmt = data.frame(k=kval, Total.Accuracy = cmaccu, row.names = NULL )  
  ResultDf = rbind(ResultDf, cmt)
  print( xkabledply(   as.matrix(cm), title = paste("ConfusionMatrix for k = ",kval ) ) )
  print( xkabledply(data.frame(cm$byClass), title=paste("k = ",kval)) )
}
``` 

```{r}
# Selected Variable Model
for (kval in 10:30) {
  online_pred_selected <- knn(train = online_training_selected, test = online_test_selected, cl=online_trainLabels_selected, k=kval)
  onlinePREDCross_selected <- CrossTable(online_testLabels_selected, online_pred_selected, prop.chisq = FALSE)
  print( paste("k = ", kval) )
  onlinePREDCross_selected
  
  cm_selected = confusionMatrix(online_pred_selected, reference = online_testLabels_selected ) 
  cmaccu_selected = cm_selected$overall['Accuracy']
  print( paste("Total Accuracy = ", cmaccu_selected ) )
   
  cmt_selected = data.frame(k=kval, Total.Accuracy = cmaccu_selected, row.names = NULL )  
  ResultDf_selected = rbind(ResultDf_selected, cmt_selected)
  print( xkabledply(   as.matrix(cm_selected), title = paste("ConfusionMatrix for k = ",kval ) ) )
  print( xkabledply(data.frame(cm_selected$byClass), title=paste("k = ",kval)) )
}
``` 

```{r, results='markup'}
xkabledply(ResultDf, "Total Accuracy Summary")
# Selected Variable Model
xkabledply(ResultDf_selected, "Total Accuracy Summary")
```


```{r}
kPlot = ggplot(ResultDf, aes(k, Total.Accuracy)) + geom_point() + geom_line()
kPlot

kPlot_selected = ggplot(ResultDf_selected, aes(k, Total.Accuracy)) + geom_point() + geom_line()
kPlot_selected
```

```{r}
# Max Accuracy
online_pred_max <- knn(train = online_training, test = online_test, cl=online_trainLabels, k=15)
onlinePREDCross_max <- CrossTable(online_testLabels, online_pred, prop.chisq = FALSE)

# Selected Variable Model
online_pred_max_selected <- knn(train = online_training_selected, test = online_test_selected, cl=online_trainLabels_selected, k=25)
onlinePREDCross_max_selected <- CrossTable(online_testLabels_selected, online_pred_selected, prop.chisq = FALSE)
```


```{r}
loadPkg("pROC")
h <- roc(online_testLabels , as.integer(online_pred_max))
auc(h)
plot(h)

h_selected <- roc(online_testLabels_selected , as.integer(online_pred_max_selected))
auc(h_selected)
plot(h_selected)
```



