---
title: "Project 2"
author: "Sanchit Vijay"
date: "2022-10-19"
output: html_document
---
```{r , include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
library(tidyverse)
library(ggplot2)
library(dplyr)
# install.packages("matrixStats")
library(matrixStats)
library(psych)
library(hrbrthemes)
library(viridis)
library(ROSE)
# library(forcats)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```


```{r, results='markup'}
#First, load the file
df_orig = data.frame(read.csv("online_shoppers_intention.csv"))
head(df_orig)
```


```{r, results='markup'}
colSums(is.na(df_orig))
```

```{r, results='markup'}
table(df_orig$Browser)
```

```{r, results='markup'}
df = data.frame(df_orig)

df$VisitorType = factor(df$VisitorType)
df$Weekend = factor(df$Weekend)
df$Revenue = factor(df$Revenue)
df$Month = factor(df$Month)

df[, c('VisitorType', 'Weekend', 'Revenue', 'Month')] <- sapply(df[, c('VisitorType', 'Weekend', 'Revenue', 'Month')], unclass)

df$VisitorType = factor(df$VisitorType)
df$Weekend = factor(df$Weekend)
df$Revenue = factor(df$Revenue)
df$Month = factor(df$Month)

head(df)
```

```{r, results='markup'}
ggplot(df_orig, aes(x=OperatingSystems, color=Revenue, fill=Revenue)) +
  # geom_histogram(bins = 8, fill="pink") + 
  # geom_freqpoly(bins=8, color="red") +
  geom_histogram(binwidth = 0.5, alpha=0.6, position = 'identity') +
  scale_color_viridis(discrete=TRUE) +
  scale_fill_viridis(discrete=TRUE) +
  scale_x_continuous(breaks=1:8) + scale_y_continuous(n.breaks=6) +
  theme_ipsum()  

ggplot(df_orig, aes(x=Browser, color=Revenue, fill=Revenue)) +
  geom_histogram(binwidth = 0.5, alpha=0.6, position = 'identity') +
  scale_x_continuous(breaks=1:13, ) + scale_y_continuous(n.breaks=6) +
  theme_ipsum() 

ggplot(df_orig, aes(x=TrafficType, color=Revenue, fill=Revenue)) +
  geom_histogram(binwidth = 1, alpha=0.6) +
  scale_fill_manual(values=c("orange", "blue")) +
  scale_x_continuous(n.breaks=20) + scale_y_continuous(n.breaks=6) + 
  theme_ipsum()  

ggplot(df_orig, aes(x=VisitorType, color=Revenue, fill=Revenue)) +
  geom_histogram(alpha=0.6, stat="count") +
  scale_fill_manual(values=c("pink", "green")) + scale_color_manual(values=c("pink", "green")) +
  theme_ipsum()  

ggplot(df_orig, aes(x=Weekend, color=Revenue, fill=Revenue)) +
  geom_histogram(alpha=0.6, stat="count") +
  scale_fill_manual(values=c("cyan", "gray")) + scale_color_manual(values=c("cyan", "gray")) +
  theme_ipsum() 

ggplot(df_orig, aes(x=Region, color=Revenue, fill=Revenue)) +
  geom_histogram(binwidth = 1, alpha=0.6, stat="count") + stat_bin(center=1) +
  scale_x_continuous(breaks=1:13, ) + scale_y_continuous(n.breaks=6) + 
  theme_ipsum() 
```

```{r, results='markup', fig.align="center", fig.width = 10, fig.height=8}
# corPlot(df, cex = 1.2)
# pairs.panels(df)
```

```{r, results='markup'}
os_contable = table(df_orig$Revenue, df_orig$OperatingSystems)
os_contable
chisq.test(os_contable, simulate.p.value=T)
```

```{r, results='markup'}
br_contable = table(df_orig$Revenue, df_orig$Browser)
br_contable
chisq.test(br_contable, simulate.p.value=T)
```

```{r, results='markup'}
rg_contable = table(df_orig$Revenue, df_orig$Region)
rg_contable
chisq.test(rg_contable, simulate.p.value=F)
```

```{r, results='markup'}
Tt_contable = table(df_orig$Revenue, df_orig$TrafficType)
Tt_contable
chisq.test(Tt_contable, simulate.p.value=T)
```

```{r, results='markup'}
Vt_contable = table(df_orig$Revenue, df_orig$VisitorType)
Vt_contable
chisq.test(Vt_contable, simulate.p.value=F)
```

```{r, results='markup'}
wk_contable = table(df_orig$Revenue, df_orig$Weekend)
wk_contable
chisq.test(wk_contable, simulate.p.value=F)
```

```{r, results='markup'}
set.seed(1234)
df_sample <- sample(2, nrow(df), replace=TRUE, prob=c(0.80, 0.20))

train <- df[df_sample==1, ]
# test_X <- df[df_sample==2, 1:17]
# 
# train_Y <- df[df_sample==1, 18]
test <- df[df_sample==2, ]
```

```{r, results='markup'}
loadPkg("rpart")

dtree_model <- rpart(Revenue ~ . - Region, data=train, method="class", control = list(maxdepth=30, cp=0.01))
printcp(dtree_model)
```


```{r, results='markup'}
loadPkg("caret") 
cm = confusionMatrix(predict(dtree_model, test, type = "class"), reference = test$Revenue, positive = "2")
cm
```

```{r, results='markup'}
library(pROC)

prob = predict(dtree_model, test, type = "class")
# df$prob=prob
h <- roc(test$Revenue ~ as.numeric(prob))
auc(h) # area-under-curve prefer 0.8 or higher.
plot(h)
```

```{r}
confusionMatrixResultDf = data.frame( Depth=numeric(0), Accuracy= numeric(0), Sensitivity=numeric(0), Specificity=numeric(0), Pos.Pred.Value=numeric(0), Neg.Pred.Value=numeric(0), Precision=numeric(0), Recall=numeric(0), F1=numeric(0), Prevalence=numeric(0), Detection.Rate=numeric(0), Detection.Prevalence=numeric(0), Balanced.Accuracy=numeric(0), row.names = NULL )

for (deep in 2:7) {
  tree_fit <- rpart(Revenue ~ . - Region, data=train, method="class", control = list(maxdepth = deep, cp=0.005) )
  # 
  cm = confusionMatrix( predict(tree_fit, test, type = "class"), reference = test[, "Revenue"], positive = "2") # from caret library
  # 
  cmaccu = cm$overall['Accuracy']
  # print( paste("Total Accuracy = ", cmaccu ) )
  # 
  cmt = data.frame(Depth=deep, Accuracy = cmaccu, row.names = NULL ) # initialize a row of the metrics 
  cmt = cbind( cmt, data.frame( t(cm$byClass) ) ) # the dataframe of the transpose, with k valued added in front
  confusionMatrixResultDf = rbind(confusionMatrixResultDf, cmt)
  # print("Other metrics : ")
}

xkabledply(confusionMatrixResultDf, title="Kyphosis Classification Trees summary with varying MaxDepth")
```


```{r, results='markup'}
dtree_model <- rpart(Revenue ~ . - Region, data=train, method="class", control = list(maxdepth = 6, cp=0.005) )
plotcp(dtree_model)
```

```{r, results='markup'}
# summary(dtree_model)
```

```{r, results='markup'}
# plot(dtree_model, uniform=TRUE, main="Classification Tree for Kyphosis")
# text(dtree_model, use.n=TRUE, all=TRUE, cex=.8, )
# post(dtree_model, file = "kythosisTree2.ps", title = "Classification Tree for Kythosis")
# loadPkg("rpart.plot")
# rpart.plot(dtree_model)
```

```{r, results='markup'}
loadPkg("rattle") # For fancyRpartPlot (Trees) Answer "no" on installing from binary source
fancyRpartPlot(dtree_model)
```

```{r, results='markup'}
prob = predict(dtree_model, test, type = "class")
# df$prob=prob
h <- roc(test$Revenue ~ as.numeric(prob))
auc(h) # area-under-curve prefer 0.8 or higher.
plot(h)
```

```{r, results='markup'}
train_os = data.frame(train)
train_new <- ovun.sample(Revenue ~ ., data = train_os, method = "over",N = 16710)$data
table(train_new$Revenue)
```

```{r, results='markup'}
dtree_model <- rpart(Revenue ~ . - Region, data=train_new, method="class", control = list(maxdepth = 6, cp=0.005) )
```

```{r, results='markup'}
confusionMatrix(predict(dtree_model, test, type = "class"), reference = test$Revenue, positive = "2")
```


```{r}
prob = predict(dtree_model, test, type = "class")
# df$prob=prob
h <- roc(test$Revenue ~ as.numeric(prob))
auc(h) # area-under-curve prefer 0.8 or higher.
plot(h)
```

